Connection builder simplification
aws/aws-iot-device-sdk-java-v2 pull request #218
Opened 2022-02-11 16:55 UTC by TwistedTwigleg

*Description of changes:*

Make a few small changes to reduce the boiler plate needed for creating an MQTT connection using the MQTT builder without breaking backwards compatibility. Now it is possible to make a connection without needing to manually create a HostResolver, EventLoopGroup, or ClientBootstrap, this can all be done automatically by the builder (and is automatically freed when done).

For RawPubSub and Greengrass samples, both are simplified but since they do not use the builder, they are not quite as simplified as other samples. However, now they do not manually create the EventLoopGroup, HostResolver, or ClientBootstrap (instead using a default static one), but because the builder wasn't used, an additional line of code is needed to free the static ClientBootstrap prior to calling `CrtResource.releaseStaticDefault` to free resources.

Note: Requires the changes in [This PR on the CRT repository(https://github.com/awslabs/aws-crt-java/pull/443) in order to function correctly.

___________

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*

2022-02-11 16:55 UTC, chong-zi commented
您好，您发给我的邮件我已收到。                                黄继龙

2022-02-28 17:06 UTC, bretambrose requested changes

2022-02-28 17:06 UTC, bretambrose commented on samples/Pkcs11PubSub/src/main/java/pkcs11pubsub/Pkcs11PubSub.java
> +                builder.withBootstrap().withConnectionEventCallbacks(callbacks).withClientId(clientId)
remove withBootstrap

2022-02-28 17:06 UTC, bretambrose commented on samples/PubSubStress/src/main/java/pubsubstress/PubSubStress.java
> +                    .withBootstrap()
remove

2022-02-28 17:06 UTC, bretambrose commented on sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java
> +    public AwsIotMqttConnectionBuilder withBootstrap() {
Remove and update build() function to use default bootstrap if necessary.

2022-02-28 17:06 UTC, bretambrose commented on samples/Shadow/src/main/java/shadow/ShadowSample.java
> +                    .withBootstrap();
remove

2022-02-28 17:53 UTC, TwistedTwigleg commented on samples/BasicPubSub/src/main/java/pubsub/PubSub.java
> +            builder.withBootstrap()
I just tested and it seems like it cannot.
I probably missing something in the CRT PR. I will take a look and see if I can figure it out.

2022-02-28 17:59 UTC, TwistedTwigleg commented on samples/BasicPubSub/src/main/java/pubsub/PubSub.java
> +            builder.withBootstrap()
Found it - there's a validation check in the V2 SDK I missed that causes it not to work. Modifying it fixes the issue and allows removing `withBootstrap`. 👍

2022-02-28 18:22 UTC, TwistedTwigleg commented
Thanks for the review! I modified the code accordingly

2022-03-02 19:20 UTC, sbSteveK approved these changes
Merge with latest changes to main, pass tests, and you're good.

2022-03-02 20:30 UTC, merged